version: '3.9'

services:

  dellocred-database:
    container_name: dellocred_crm_database
    build:
      context: ./dellocred-database
    image: dellocred-crm-database:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  dellocred-backend:
    container_name: dellocred_crm_backend
    build:
      context: ./dellocred-backend
    image: dellocred-crm-backend:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=dellocred_backend.settings
    depends_on:
      - dellocred-database

  dellocred-frontend:
    container_name: dellocred_crm_frontend
    build:
      context: ./dellocred-frontend
    image: dellocred-crm-frontend:latest
    ports:
      - "80:80"

volumes:
  pgdata: