version: '3.9'

services:

  dellocred-database:
    image: postgres:latest
    container_name: dellocred_crm_database
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/mysql
    networks:
      - dellocred-net

  dellocred-backend:
    build:
      dockerfile: Dockerfile
    image: dellocred-crm-backend:latest
    container_name: dellocred_crm_backend      
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - dellocred-net
    command: sh -c "sleep 10 && npm run start:dev"
    depends_on:
      - dellocred-database

networks:
  dellocred-net:
    driver: bridge

volumes:
  pgdata: