# Generated by Django 5.2.1 on 2025-06-23 16:16

import clients.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9ce80845-0d31-45ed-8502-39c721f4eaf8'), editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=11, unique=True, validators=[clients.models.validate_national_id])),
                ('first_name', models.CharField(default=None, max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=254, unique=True, validators=[clients.models.validate_email])),
                ('phone_number', models.CharField(default=None, max_length=20, unique=True)),
                ('birth_date', models.DateField(null=True)),
                ('profession', models.CharField(null=True, unique=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=2, null=True, validators=[clients.models.validate_state])),
                ('city', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('address_number', models.CharField(max_length=50, null=True)),
                ('address_complement', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
